### ISSUE TITLE
101 link to video broken

### ISSUE THREAD

**Issue by jgravois** [openwichita/docs#6]
ref: https://github.com/openwichita/docs/blob/master/civic-hacking-101.md#one-more-thing

> you should really [watch this video](https://github.com/openwichita/docs/blob/master/civic-hacking-101-video) ... Do it, [watch the video](https://github.com/openwichita/docs/blob/master/civic-hacking-101-video). You won't reget it.

bad url: https://github.com/openwichita/docs/blob/master/civic-hacking-101-video

sounds so exciting i trolled around in your other repo for a couple minutes looking but like a 👻 , the video eluded me.

**Comment by jgravois** [comment]
also, you missed the **"r"** in the middle of *regret*.

**Comment by sethetter** [comment]
@jgravois thanks for catching that! I'll take care of it.
